### ISSUE TITLE
[Q] why such syntax?

### ISSUE THREAD

**Issue by Bia10** [KernalsEgg/NetScriptFramework#1]
I like the ideas being developed here, however i have to say i have never seen such a style to write C# code could you please clarify what are the reasons for such a syntax is there any performance/size benefit at all?

what do i mean?

- usage of fully qualified names
- usage of .NET types rather then C# types
- extra empty lines
- incorrect order of modifiers

**Comment by KernalsEgg** [comment]
I will preface this by saying that while I am happy to make it available, I didn't write it with the intention for other people to use it and have to suffer through my unique stylings. That being said, obviously feel free to.

The usage of fully qualified names was born from having several classes in different namespaces with the same name. For example, each of the fixes and patches have their own classes, and there are also classes with the same names in the Offsets and Patterns namespaces. The Offsets and Patterns namespaces also both exist in the Eggstensions and ScrambledBugs namespaces. So, this was my attempt to add readability, which can sometimes get out of hand.

I write `System.Int32` and `System.Int64` instead of `int` and `long` for example because the width is important in the context of reverse engineering and I feel that it adds readability. In [CommonLibSSE](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE) you will similarly see `std::int32_t` and `std::int64_t` being used instead of `int` and `long`.

There is no good reason behind the extra empty lines beyond the fact that I frequently scan through my code and I find that they help. They're another thing that I get carried away with, and I can understand if you dislike it.

Can you please be more specific regarding the incorrect order of modifiers? Links to specific lines would be ideal. If you have spotted a bug then I would prefer to fix it, haha.

**Comment by Bia10** [comment]
Thanks for clarifying, i was worried this had to do with some kind of speed/size optimization based on advanced knowledge of build process, now that i can see the reasons are more "down to the earth" i can rely.

> The usage of fully qualified names was born from having several classes in different namespaces with the same name. For example, each of the fixes and patches have their own classes, and there are also classes with the same names in the Offsets and Patterns namespaces. The Offsets and Patterns namespaces also both exist in the Eggstensions and ScrambledBugs namespaces. So, this was my attempt to add readability, which can sometimes get out of hand.

Understandable, not my style tho.

> I write `System.Int32` and `System.Int64` instead of `int` and `long` for example because the width is important in the context of reverse engineering and I feel that it adds readability. In [CommonLibSSE](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE) you will similarly see `std::int32_t` and `std::int64_t` being used instead of `int` and `long`.

Well is this the only reason to fully justify use of .NET types literally everywhere? I find it kind of funny to see a complex type being just var and under it rigorously specifying System.String rather then just string. I just don't think that this reason is sufficient for such widespread usage, where knowledge of width is needed i do see the point.

> There is no good reason behind the extra empty lines beyond the fact that I frequently scan through my code and I find that they help. They're another thing that I get carried away with, and I can understand if you dislike it.

I see, well id prefer using Regions rather then extra spaces to increase readability.

> Can you please be more specific regarding the incorrect order of modifiers? Links to specific lines would be ideal. If you have spotted a bug then I would prefer to fix it, haha.

I apologize for this misunderstanding, since neither of us has specified the followed convention on ordering of modifiers the word incorrect is inappropriate.

you write `unsafe static public class Assembly` 
i would write `public static unsafe class Assembly`

you write `static public`
i write `public static`

**Comment by KernalsEgg** [comment]
> Well is this the only reason to fully justify use of .NET types literally everywhere?

I have at times for example had namespaces and classes with the same names as blittable types to assist with marshalling. So, for this and other similar reasons I chose to always use fully qualified type names, and have yet to change it.

> I see, well id prefer using Regions rather then extra spaces to increase readability.

Regions require more button presses, so you can say that I took the easy way out. It's something that I have considered changing.

> you write `unsafe static public class Assembly`
i would write `public static unsafe class Assembly`

I ordered the modifiers based on what I first look for when quickly scanning through my code. It's just another of the decisions I made with the expectation that I would be the only person working with the code.

**Comment by Bia10** [comment]
Thanks for clarifying, currently i am in process of refactoring this into less unique style and uncoupling the skse part, i see this as more generic framework for more games then just skyrim or skse. Well see how things go. 

I hope you don't mind if i ask if something unclear comes up.

**Comment by KernalsEgg** [comment]
While there are changes I would make, hopefully it helps you with what you are working on.

There are a couple of bugs with C# 9.0 function pointers that I suggest you keep in mind. I tried to explain them [here](https://github.com/KernalsEgg/NetScriptFramework/blob/master/Eggstensions/Eggstensions/Main.cs#L4), though it is poorly worded, so I will try to make it clearer.

When the JIT Compiler optimises calls to function pointers at runtime, it can cause crashes. Specifically, I believe it can optimise blittable types into non-blittable types. For example, if you convert a `System.Boolean` into a `System.Byte` using the `?:` operator.

The only way I have been able to fix this for certain is by moving the function pointer call to a separate function with the NoInlining attribute. If this is not done for the [GetEquippedWeapon function](https://github.com/KernalsEgg/NetScriptFramework/blob/master/Eggstensions/Eggstensions/A/Actor.cs#L107) for example, the game will usually crash within 5 function calls.

Strictly speaking, this is only necessary if you convert a non-blittable type into a blittable type. However, I do this for every function pointer for peace of mind. It does obviously cost you in performance, though function pointers are still significantly faster than the delegates I was previously using in C# 7.3.

The second bug also causes crashes, which occurs when you call a static function pointer property that is initialized inline when you declare it. For example, if in the scope of a class you write:
`public static delegate* unmanaged[Cdecl]<Actor*, System.Byte, TESObjectWEAP*> GetEquippedWeapon { get; } = Memory.ReadRelativeCall(address);`

The game will crash when you call the `GetEquippedWeapon` function pointer. You must instead set the function pointer in a function, like I do [here](https://github.com/KernalsEgg/NetScriptFramework/blob/master/ScrambledBugs/ScrambledBugs/Fixes/HarvestedFlags.cs#L30). I could be wrong, but I do remember this crash being consistent. I don't know why this crash occurs.

If you can clarify anything or know of better solutions, please let me know.
